In [1]:
import pandas as pd
import numpy as np

In [2]:
movie_data = pd.read_csv("movies.csv")
rating_data = pd.read_csv("ratings.csv")
links_data = pd.read_csv("links.csv")
tag_data = pd.read_csv("tags.csv")

In [3]:
#film_A = 1
#film_A = 191483 # The Nun (2018)    2179136
#film_A = 106696 # frozen (2013)
#film_A = 85788 # insidios (2010)
#film_A = 114662 # american sniper
film_A =  1 #toy story

här sätter folk betyget och vi sorterar att dom måste minst gett en 4a för att få vara en offentlig röst

In [4]:
liking_film_A = rating_data[
    (rating_data["movieId"] == film_A) & 
    (rating_data["rating"] >= 4.0) #minst 4 i betyg
            ].sort_values("userId")

ta alla filmer

In [5]:
users_A = liking_film_A["userId"].unique()

alla gillare från film A som gillar andra filmer

In [6]:
rekommend = rating_data[
    (rating_data["userId"].isin(users_A))&
    (rating_data["movieId"] != film_A)&
    (rating_data["rating"] >= 4)
            ].groupby("movieId").size()

rating_count = rating_data.groupby("movieId").size()

In [7]:
rating_count

movieId
1         76813
2         30209
3         15820
4          3028
5         15801
          ...
288967        1
288971        1
288975        1
288977        1
288983        1
Length: 83239, dtype: int64

In [8]:

rekommend = rekommend / len(users_A)
rekommend = rekommend / np.sqrt(rating_count)

In [9]:
score = rekommend / len(users_A)

In [10]:
try_top15 = (score.sort_values(ascending=False).head(25))

In [11]:
top15_score = try_top15.reset_index()
top15_score.columns = ["movieId", "score"]

top15 = top15_score.merge(movie_data, on="movieId")
top15

,movieId,score,title,genres
0,3114,3.308806e-08,Toy Story 2 (1999),Adventure|Animation|Children|Comedy|Fantasy
1,260,3.202292e-08,Star Wars: Episode IV - A New Hope (1977),Action|Adventure|Sci-Fi
2,1270,2.946561e-08,Back to the Future (1985),Adventure|Comedy|Sci-Fi
3,318,2.936978e-08,"Shawshank Redemption, The (1994)",Crime|Drama
4,1196,2.912265e-08,Star Wars: Episode V - The Empire Strikes Back...,Action|Adventure|Sci-Fi
5,356,2.897444e-08,Forrest Gump (1994),Comedy|Drama|Romance|War
6,1198,2.853479e-08,Raiders of the Lost Ark (Indiana Jones and the...,Action|Adventure
7,1210,2.815118e-08,Star Wars: Episode VI - Return of the Jedi (1983),Action|Adventure|Sci-Fi
8,364,2.794082e-08,"Lion King, The (1994)",Adventure|Animation|Children|Drama|Musical|IMAX
9,296,2.773451e-08,Pulp Fiction (1994),Comedy|Crime|Drama|Thriller
10,4886,2.734617e-08,"Monsters, Inc. (2001)",Adventure|Animation|Children|Comedy|Fantasy
11,2571,2.734319e-08,"Matrix, The (1999)",Action|Sci-Fi|Thriller
12,593,2.703503e-08,"Silence of the Lambs, The (1991)",Crime|Horror|Thriller
13,1197,2.627298e-08,"Princess Bride, The (1987)",Action|Adventure|Comedy|Fantasy|Romance
14,608,2.613629e-08,Fargo (1996),Comedy|Crime|Drama|Thriller
15,6377,2.598167e-08,Finding Nemo (2003),Adventure|Animation|Children|Comedy
16,50,2.574080e-08,"Usual Suspects, The (1995)",Crime|Mystery|Thriller
17,1136,2.564260e-08,Monty Python and the Holy Grail (1975),Adventure|Comedy|Fantasy
18,1265,2.562540e-08,Groundhog Day (1993),Comedy|Fantasy|Romance
19,589,2.558513e-08,Terminator 2: Judgment Day (1991),Action|Sci-Fi
20,1291,2.521857e-08,Indiana Jones and the Last Crusade (1989),Action|Adventure
21,588,2.520481e-08,Aladdin (1992),Adventure|Animation|Children|Comedy|Musical
22,527,2.513524e-08,Schindler's List (1993),Drama|War
23,47,2.489868e-08,Seven (a.k.a. Se7en) (1995),Mystery|Thriller
24,8961,2.484293e-08,"Incredibles, The (2004)",Action|Adventure|Animation|Children|Comedy

In [12]:
movie_data["year"] = movie_data["title"].str.extract(r"\((\d{4})\)").astype(float)

In [13]:
year_a = movie_data.loc[movie_data["movieId"] == film_A, "year"].iloc[0]
year_a

np.float64(1995.0)

In [14]:
top15_year = top15.merge(movie_data, on=["movieId", "title", "genres"])
top15_year

,movieId,score,title,genres,year
0,3114,3.308806e-08,Toy Story 2 (1999),Adventure|Animation|Children|Comedy|Fantasy,1999.0
1,260,3.202292e-08,Star Wars: Episode IV - A New Hope (1977),Action|Adventure|Sci-Fi,1977.0
2,1270,2.946561e-08,Back to the Future (1985),Adventure|Comedy|Sci-Fi,1985.0
3,318,2.936978e-08,"Shawshank Redemption, The (1994)",Crime|Drama,1994.0
4,1196,2.912265e-08,Star Wars: Episode V - The Empire Strikes Back...,Action|Adventure|Sci-Fi,1980.0
5,356,2.897444e-08,Forrest Gump (1994),Comedy|Drama|Romance|War,1994.0
6,1198,2.853479e-08,Raiders of the Lost Ark (Indiana Jones and the...,Action|Adventure,1981.0
7,1210,2.815118e-08,Star Wars: Episode VI - Return of the Jedi (1983),Action|Adventure|Sci-Fi,1983.0
8,364,2.794082e-08,"Lion King, The (1994)",Adventure|Animation|Children|Drama|Musical|IMAX,1994.0
9,296,2.773451e-08,Pulp Fiction (1994),Comedy|Crime|Drama|Thriller,1994.0
10,4886,2.734617e-08,"Monsters, Inc. (2001)",Adventure|Animation|Children|Comedy|Fantasy,2001.0
11,2571,2.734319e-08,"Matrix, The (1999)",Action|Sci-Fi|Thriller,1999.0
12,593,2.703503e-08,"Silence of the Lambs, The (1991)",Crime|Horror|Thriller,1991.0
13,1197,2.627298e-08,"Princess Bride, The (1987)",Action|Adventure|Comedy|Fantasy|Romance,1987.0
14,608,2.613629e-08,Fargo (1996),Comedy|Crime|Drama|Thriller,1996.0
15,6377,2.598167e-08,Finding Nemo (2003),Adventure|Animation|Children|Comedy,2003.0
16,50,2.574080e-08,"Usual Suspects, The (1995)",Crime|Mystery|Thriller,1995.0
17,1136,2.564260e-08,Monty Python and the Holy Grail (1975),Adventure|Comedy|Fantasy,1975.0
18,1265,2.562540e-08,Groundhog Day (1993),Comedy|Fantasy|Romance,1993.0
19,589,2.558513e-08,Terminator 2: Judgment Day (1991),Action|Sci-Fi,1991.0
20,1291,2.521857e-08,Indiana Jones and the Last Crusade (1989),Action|Adventure,1989.0
21,588,2.520481e-08,Aladdin (1992),Adventure|Animation|Children|Comedy|Musical,1992.0
22,527,2.513524e-08,Schindler's List (1993),Drama|War,1993.0
23,47,2.489868e-08,Seven (a.k.a. Se7en) (1995),Mystery|Thriller,1995.0
24,8961,2.484293e-08,"Incredibles, The (2004)",Action|Adventure|Animation|Children|Comedy,2004.0

In [15]:
diffrens_in_years = abs(top15_year["year"] - year_a)
year_diffrens = diffrens_in_years.reset_index()

In [16]:
# for i in range(len(diffrens_in_years)):
#     bonus = 0
#     if int(year_diffrens["year"].loc[i]) <= 2:
#         bonus = 0.1
#         top15_year.loc[i, "score"] += bonus
#     elif int(year_diffrens["year"].loc[i]) <= 5:
#         bonus = 0.06
#         top15_year.loc[i, "score"] += bonus
#     elif int(year_diffrens["year"].loc[i]) <= 8:
#         bonus = 0.03
#         top15_year.loc[i, "score"] += bonus

#     else:
#         top15_year.loc[i, "score"]

In [17]:
top = top15_year.sort_values("score", ascending=False)
top

,movieId,score,title,genres,year
0,3114,3.308806e-08,Toy Story 2 (1999),Adventure|Animation|Children|Comedy|Fantasy,1999.0
1,260,3.202292e-08,Star Wars: Episode IV - A New Hope (1977),Action|Adventure|Sci-Fi,1977.0
2,1270,2.946561e-08,Back to the Future (1985),Adventure|Comedy|Sci-Fi,1985.0
3,318,2.936978e-08,"Shawshank Redemption, The (1994)",Crime|Drama,1994.0
4,1196,2.912265e-08,Star Wars: Episode V - The Empire Strikes Back...,Action|Adventure|Sci-Fi,1980.0
5,356,2.897444e-08,Forrest Gump (1994),Comedy|Drama|Romance|War,1994.0
6,1198,2.853479e-08,Raiders of the Lost Ark (Indiana Jones and the...,Action|Adventure,1981.0
7,1210,2.815118e-08,Star Wars: Episode VI - Return of the Jedi (1983),Action|Adventure|Sci-Fi,1983.0
8,364,2.794082e-08,"Lion King, The (1994)",Adventure|Animation|Children|Drama|Musical|IMAX,1994.0
9,296,2.773451e-08,Pulp Fiction (1994),Comedy|Crime|Drama|Thriller,1994.0
10,4886,2.734617e-08,"Monsters, Inc. (2001)",Adventure|Animation|Children|Comedy|Fantasy,2001.0
11,2571,2.734319e-08,"Matrix, The (1999)",Action|Sci-Fi|Thriller,1999.0
12,593,2.703503e-08,"Silence of the Lambs, The (1991)",Crime|Horror|Thriller,1991.0
13,1197,2.627298e-08,"Princess Bride, The (1987)",Action|Adventure|Comedy|Fantasy|Romance,1987.0
14,608,2.613629e-08,Fargo (1996),Comedy|Crime|Drama|Thriller,1996.0
15,6377,2.598167e-08,Finding Nemo (2003),Adventure|Animation|Children|Comedy,2003.0
16,50,2.574080e-08,"Usual Suspects, The (1995)",Crime|Mystery|Thriller,1995.0
17,1136,2.564260e-08,Monty Python and the Holy Grail (1975),Adventure|Comedy|Fantasy,1975.0
18,1265,2.562540e-08,Groundhog Day (1993),Comedy|Fantasy|Romance,1993.0
19,589,2.558513e-08,Terminator 2: Judgment Day (1991),Action|Sci-Fi,1991.0
20,1291,2.521857e-08,Indiana Jones and the Last Crusade (1989),Action|Adventure,1989.0
21,588,2.520481e-08,Aladdin (1992),Adventure|Animation|Children|Comedy|Musical,1992.0
22,527,2.513524e-08,Schindler's List (1993),Drama|War,1993.0
23,47,2.489868e-08,Seven (a.k.a. Se7en) (1995),Mystery|Thriller,1995.0
24,8961,2.484293e-08,"Incredibles, The (2004)",Action|Adventure|Animation|Children|Comedy,2004.0

In [18]:
a = movie_data[movie_data["movieId"] == film_A]
A = a["genres"].iloc[0].split("|")
A

['Adventure', 'Animation', 'Children', 'Comedy', 'Fantasy']

In [19]:
# A = movie_data[movie_data["movieId"] == film_A]["genres"].iloc[0].split("|")

# for i, genres in enumerate(top["genres"]):

#     genre_list = genres.split("|")

#     matches = 0

#     for g in genre_list:
#         if g in A:
#             matches += 1

#     if matches > 0:
#         print(top["title"].iloc[i])
#         top.loc[i, "score"] += matches * 0.25

In [20]:
A = movie_data[movie_data["movieId"] == film_A]["genres"].iloc[0].split("|")

for i, genres in enumerate(top["genres"]):

    genre_list = genres.split("|")

    matches = 0

    for g in genre_list:
        if g in A:
            matches += 1

    if matches > 0:
        similarity = matches / len(A)
        print(top["title"].iloc[i])
        top.loc[i, "score"] += similarity

Toy Story 2 (1999)
Star Wars: Episode IV - A New Hope (1977)
Back to the Future (1985)
Star Wars: Episode V - The Empire Strikes Back (1980)
Forrest Gump (1994)
Raiders of the Lost Ark (Indiana Jones and the Raiders of the Lost Ark) (1981)
Star Wars: Episode VI - Return of the Jedi (1983)
Lion King, The (1994)
Pulp Fiction (1994)
Monsters, Inc. (2001)
Princess Bride, The (1987)
Fargo (1996)
Finding Nemo (2003)
Monty Python and the Holy Grail (1975)
Groundhog Day (1993)
Indiana Jones and the Last Crusade (1989)
Aladdin (1992)
Incredibles, The (2004)

In [21]:
top.sort_values("score",ascending=False)

,movieId,score,title,genres,year
0,3114,1.000000e+00,Toy Story 2 (1999),Adventure|Animation|Children|Comedy|Fantasy,1999.0
10,4886,1.000000e+00,"Monsters, Inc. (2001)",Adventure|Animation|Children|Comedy|Fantasy,2001.0
15,6377,8.000000e-01,Finding Nemo (2003),Adventure|Animation|Children|Comedy,2003.0
21,588,8.000000e-01,Aladdin (1992),Adventure|Animation|Children|Comedy|Musical,1992.0
24,8961,8.000000e-01,"Incredibles, The (2004)",Action|Adventure|Animation|Children|Comedy,2004.0
8,364,6.000000e-01,"Lion King, The (1994)",Adventure|Animation|Children|Drama|Musical|IMAX,1994.0
13,1197,6.000000e-01,"Princess Bride, The (1987)",Action|Adventure|Comedy|Fantasy|Romance,1987.0
17,1136,6.000000e-01,Monty Python and the Holy Grail (1975),Adventure|Comedy|Fantasy,1975.0
2,1270,4.000000e-01,Back to the Future (1985),Adventure|Comedy|Sci-Fi,1985.0
18,1265,4.000000e-01,Groundhog Day (1993),Comedy|Fantasy|Romance,1993.0
1,260,2.000000e-01,Star Wars: Episode IV - A New Hope (1977),Action|Adventure|Sci-Fi,1977.0
4,1196,2.000000e-01,Star Wars: Episode V - The Empire Strikes Back...,Action|Adventure|Sci-Fi,1980.0
5,356,2.000000e-01,Forrest Gump (1994),Comedy|Drama|Romance|War,1994.0
6,1198,2.000000e-01,Raiders of the Lost Ark (Indiana Jones and the...,Action|Adventure,1981.0
7,1210,2.000000e-01,Star Wars: Episode VI - Return of the Jedi (1983),Action|Adventure|Sci-Fi,1983.0
9,296,2.000000e-01,Pulp Fiction (1994),Comedy|Crime|Drama|Thriller,1994.0
14,608,2.000000e-01,Fargo (1996),Comedy|Crime|Drama|Thriller,1996.0
20,1291,2.000000e-01,Indiana Jones and the Last Crusade (1989),Action|Adventure,1989.0
3,318,2.936978e-08,"Shawshank Redemption, The (1994)",Crime|Drama,1994.0
11,2571,2.734319e-08,"Matrix, The (1999)",Action|Sci-Fi|Thriller,1999.0
12,593,2.703503e-08,"Silence of the Lambs, The (1991)",Crime|Horror|Thriller,1991.0
16,50,2.574080e-08,"Usual Suspects, The (1995)",Crime|Mystery|Thriller,1995.0
19,589,2.558513e-08,Terminator 2: Judgment Day (1991),Action|Sci-Fi,1991.0
22,527,2.513524e-08,Schindler's List (1993),Drama|War,1993.0
23,47,2.489868e-08,Seven (a.k.a. Se7en) (1995),Mystery|Thriller,1995.0

In [22]:
top.sort_values("score",ascending=False).head(5)

,movieId,score,title,genres,year
0,3114,1.0,Toy Story 2 (1999),Adventure|Animation|Children|Comedy|Fantasy,1999.0
10,4886,1.0,"Monsters, Inc. (2001)",Adventure|Animation|Children|Comedy|Fantasy,2001.0
15,6377,0.8,Finding Nemo (2003),Adventure|Animation|Children|Comedy,2003.0
21,588,0.8,Aladdin (1992),Adventure|Animation|Children|Comedy|Musical,1992.0
24,8961,0.8,"Incredibles, The (2004)",Action|Adventure|Animation|Children|Comedy,2004.0