In [1]:
import pandas as pd

In [2]:
movie_data = pd.read_csv("movies.csv")
rating_data = pd.read_csv("ratings.csv")
links_data = pd.read_csv("links.csv")
tag_data = pd.read_csv("tags.csv")

In [3]:
#film_A = 1
#film_A = 191483 # The Nun (2018)    2179136
#film_A = 106696 # frozen (2013)
#film_A = 85788 # insidios (2010)
#film_A = 114662 # american sniper
film_A =  1 #toy story

här sätter folk betyget och vi sorterar att dom måste minst gett en 4a för att få vara en offentlig röst

In [4]:
liking_film_A = rating_data[
    (rating_data["movieId"] == film_A) & 
    (rating_data["rating"] >= 4.0) #minst 4 i betyg
            ].sort_values("userId")

ta alla filmer

In [5]:
users_A = liking_film_A["userId"].unique()

alla gillare från film A som gillar andra filmer

In [ ]:
rekommend = rating_data[
    (rating_data["userId"].isin(users_A))&
    (rating_data["movieId"] != film_A)&
    (rating_data["rating"] >= 4)
            ].groupby("movieId").size()

rating_count = rating_data.groupby("movieId").size()

rekommend = rekommend[rating_count >= 150]

In [7]:
score = rekommend / len(users_A)

In [8]:
try_top15 = (score.sort_values(ascending=False).head(25))

In [9]:
top15_score = try_top15.reset_index()
top15_score.columns = ["movieId", "score"]

top15 = top15_score.merge(movie_data, on="movieId")
top15

,movieId,score,title,genres
0,318,0.519418,"Shawshank Redemption, The (1994)",Crime|Drama
1,260,0.504904,Star Wars: Episode IV - A New Hope (1977),Action|Adventure|Sci-Fi
2,356,0.493831,Forrest Gump (1994),Comedy|Drama|Romance|War
3,296,0.462548,Pulp Fiction (1994),Comedy|Crime|Drama|Thriller
4,2571,0.452444,"Matrix, The (1999)",Action|Sci-Fi|Thriller
5,593,0.436230,"Silence of the Lambs, The (1991)",Crime|Horror|Thriller
6,1196,0.417089,Star Wars: Episode V - The Empire Strikes Back...,Action|Adventure|Sci-Fi
7,1198,0.395851,Raiders of the Lost Ark (Indiana Jones and the...,Action|Adventure
8,1210,0.394467,Star Wars: Episode VI - Return of the Jedi (1983),Action|Adventure|Sci-Fi
9,1270,0.387942,Back to the Future (1985),Adventure|Comedy|Sci-Fi
10,527,0.368920,Schindler's List (1993),Drama|War
11,4993,0.354504,"Lord of the Rings: The Fellowship of the Ring,...",Adventure|Fantasy
12,480,0.353318,Jurassic Park (1993),Action|Adventure|Sci-Fi|Thriller
13,50,0.351459,"Usual Suspects, The (1995)",Crime|Mystery|Thriller
14,589,0.346753,Terminator 2: Judgment Day (1991),Action|Sci-Fi
15,2959,0.340188,Fight Club (1999),Action|Crime|Drama|Thriller
16,858,0.337479,"Godfather, The (1972)",Crime|Drama
17,110,0.333762,Braveheart (1995),Action|Drama|War
18,608,0.329056,Fargo (1996),Comedy|Crime|Drama|Thriller
19,364,0.326861,"Lion King, The (1994)",Adventure|Animation|Children|Drama|Musical|IMAX
20,5952,0.324053,"Lord of the Rings: The Two Towers, The (2002)",Adventure|Fantasy
21,47,0.322669,Seven (a.k.a. Se7en) (1995),Mystery|Thriller
22,7153,0.319801,"Lord of the Rings: The Return of the King, The...",Action|Adventure|Drama|Fantasy
23,2028,0.311121,Saving Private Ryan (1998),Action|Drama|War
24,3114,0.310785,Toy Story 2 (1999),Adventure|Animation|Children|Comedy|Fantasy

In [10]:
movie_data["year"] = movie_data["title"].str.extract(r"\((\d{4})\)").astype(float)

In [11]:
year_a = movie_data.loc[movie_data["movieId"] == film_A, "year"].iloc[0]
year_a

np.float64(1995.0)

In [12]:
top15_year = top15.merge(movie_data, on=["movieId", "title", "genres"])
top15_year

,movieId,score,title,genres,year
0,318,0.519418,"Shawshank Redemption, The (1994)",Crime|Drama,1994.0
1,260,0.504904,Star Wars: Episode IV - A New Hope (1977),Action|Adventure|Sci-Fi,1977.0
2,356,0.493831,Forrest Gump (1994),Comedy|Drama|Romance|War,1994.0
3,296,0.462548,Pulp Fiction (1994),Comedy|Crime|Drama|Thriller,1994.0
4,2571,0.452444,"Matrix, The (1999)",Action|Sci-Fi|Thriller,1999.0
5,593,0.436230,"Silence of the Lambs, The (1991)",Crime|Horror|Thriller,1991.0
6,1196,0.417089,Star Wars: Episode V - The Empire Strikes Back...,Action|Adventure|Sci-Fi,1980.0
7,1198,0.395851,Raiders of the Lost Ark (Indiana Jones and the...,Action|Adventure,1981.0
8,1210,0.394467,Star Wars: Episode VI - Return of the Jedi (1983),Action|Adventure|Sci-Fi,1983.0
9,1270,0.387942,Back to the Future (1985),Adventure|Comedy|Sci-Fi,1985.0
10,527,0.368920,Schindler's List (1993),Drama|War,1993.0
11,4993,0.354504,"Lord of the Rings: The Fellowship of the Ring,...",Adventure|Fantasy,2001.0
12,480,0.353318,Jurassic Park (1993),Action|Adventure|Sci-Fi|Thriller,1993.0
13,50,0.351459,"Usual Suspects, The (1995)",Crime|Mystery|Thriller,1995.0
14,589,0.346753,Terminator 2: Judgment Day (1991),Action|Sci-Fi,1991.0
15,2959,0.340188,Fight Club (1999),Action|Crime|Drama|Thriller,1999.0
16,858,0.337479,"Godfather, The (1972)",Crime|Drama,1972.0
17,110,0.333762,Braveheart (1995),Action|Drama|War,1995.0
18,608,0.329056,Fargo (1996),Comedy|Crime|Drama|Thriller,1996.0
19,364,0.326861,"Lion King, The (1994)",Adventure|Animation|Children|Drama|Musical|IMAX,1994.0
20,5952,0.324053,"Lord of the Rings: The Two Towers, The (2002)",Adventure|Fantasy,2002.0
21,47,0.322669,Seven (a.k.a. Se7en) (1995),Mystery|Thriller,1995.0
22,7153,0.319801,"Lord of the Rings: The Return of the King, The...",Action|Adventure|Drama|Fantasy,2003.0
23,2028,0.311121,Saving Private Ryan (1998),Action|Drama|War,1998.0
24,3114,0.310785,Toy Story 2 (1999),Adventure|Animation|Children|Comedy|Fantasy,1999.0

In [13]:
diffrens_in_years = abs(top15_year["year"] - year_a)
year_diffrens = diffrens_in_years.reset_index()

In [14]:
# for i in range(len(diffrens_in_years)):
#     bonus = 0
#     if int(year_diffrens["year"].loc[i]) <= 2:
#         bonus = 0.1
#         top15_year.loc[i, "score"] += bonus
#     elif int(year_diffrens["year"].loc[i]) <= 5:
#         bonus = 0.06
#         top15_year.loc[i, "score"] += bonus
#     elif int(year_diffrens["year"].loc[i]) <= 8:
#         bonus = 0.03
#         top15_year.loc[i, "score"] += bonus

#     else:
#         top15_year.loc[i, "score"]

In [15]:
top = top15_year.sort_values("score", ascending=False)
top

,movieId,score,title,genres,year
0,318,0.519418,"Shawshank Redemption, The (1994)",Crime|Drama,1994.0
1,260,0.504904,Star Wars: Episode IV - A New Hope (1977),Action|Adventure|Sci-Fi,1977.0
2,356,0.493831,Forrest Gump (1994),Comedy|Drama|Romance|War,1994.0
3,296,0.462548,Pulp Fiction (1994),Comedy|Crime|Drama|Thriller,1994.0
4,2571,0.452444,"Matrix, The (1999)",Action|Sci-Fi|Thriller,1999.0
5,593,0.436230,"Silence of the Lambs, The (1991)",Crime|Horror|Thriller,1991.0
6,1196,0.417089,Star Wars: Episode V - The Empire Strikes Back...,Action|Adventure|Sci-Fi,1980.0
7,1198,0.395851,Raiders of the Lost Ark (Indiana Jones and the...,Action|Adventure,1981.0
8,1210,0.394467,Star Wars: Episode VI - Return of the Jedi (1983),Action|Adventure|Sci-Fi,1983.0
9,1270,0.387942,Back to the Future (1985),Adventure|Comedy|Sci-Fi,1985.0
10,527,0.368920,Schindler's List (1993),Drama|War,1993.0
11,4993,0.354504,"Lord of the Rings: The Fellowship of the Ring,...",Adventure|Fantasy,2001.0
12,480,0.353318,Jurassic Park (1993),Action|Adventure|Sci-Fi|Thriller,1993.0
13,50,0.351459,"Usual Suspects, The (1995)",Crime|Mystery|Thriller,1995.0
14,589,0.346753,Terminator 2: Judgment Day (1991),Action|Sci-Fi,1991.0
15,2959,0.340188,Fight Club (1999),Action|Crime|Drama|Thriller,1999.0
16,858,0.337479,"Godfather, The (1972)",Crime|Drama,1972.0
17,110,0.333762,Braveheart (1995),Action|Drama|War,1995.0
18,608,0.329056,Fargo (1996),Comedy|Crime|Drama|Thriller,1996.0
19,364,0.326861,"Lion King, The (1994)",Adventure|Animation|Children|Drama|Musical|IMAX,1994.0
20,5952,0.324053,"Lord of the Rings: The Two Towers, The (2002)",Adventure|Fantasy,2002.0
21,47,0.322669,Seven (a.k.a. Se7en) (1995),Mystery|Thriller,1995.0
22,7153,0.319801,"Lord of the Rings: The Return of the King, The...",Action|Adventure|Drama|Fantasy,2003.0
23,2028,0.311121,Saving Private Ryan (1998),Action|Drama|War,1998.0
24,3114,0.310785,Toy Story 2 (1999),Adventure|Animation|Children|Comedy|Fantasy,1999.0

In [16]:
a = movie_data[movie_data["movieId"] == film_A]
A = a["genres"].iloc[0].split("|")
A

['Adventure', 'Animation', 'Children', 'Comedy', 'Fantasy']

In [17]:
# A = movie_data[movie_data["movieId"] == film_A]["genres"].iloc[0].split("|")

# for i, genres in enumerate(top["genres"]):

#     genre_list = genres.split("|")

#     matches = 0

#     for g in genre_list:
#         if g in A:
#             matches += 1

#     if matches > 0:
#         print(top["title"].iloc[i])
#         top.loc[i, "score"] += matches * 0.25

In [18]:
A = movie_data[movie_data["movieId"] == film_A]["genres"].iloc[0].split("|")

for i, genres in enumerate(top["genres"]):

    genre_list = genres.split("|")

    matches = 0

    for g in genre_list:
        if g in A:
            matches += 1

    if matches > 0:
        similarity = matches / len(A)
        print(top["title"].iloc[i])
        top.loc[i, "score"] += similarity

Star Wars: Episode IV - A New Hope (1977)
Forrest Gump (1994)
Pulp Fiction (1994)
Star Wars: Episode V - The Empire Strikes Back (1980)
Raiders of the Lost Ark (Indiana Jones and the Raiders of the Lost Ark) (1981)
Star Wars: Episode VI - Return of the Jedi (1983)
Back to the Future (1985)
Lord of the Rings: The Fellowship of the Ring, The (2001)
Jurassic Park (1993)
Fargo (1996)
Lion King, The (1994)
Lord of the Rings: The Two Towers, The (2002)
Lord of the Rings: The Return of the King, The (2003)
Toy Story 2 (1999)

In [19]:
top.sort_values("score",ascending=False)

,movieId,score,title,genres,year
24,3114,1.310785,Toy Story 2 (1999),Adventure|Animation|Children|Comedy|Fantasy,1999.0
19,364,0.926861,"Lion King, The (1994)",Adventure|Animation|Children|Drama|Musical|IMAX,1994.0
9,1270,0.787942,Back to the Future (1985),Adventure|Comedy|Sci-Fi,1985.0
11,4993,0.754504,"Lord of the Rings: The Fellowship of the Ring,...",Adventure|Fantasy,2001.0
20,5952,0.724053,"Lord of the Rings: The Two Towers, The (2002)",Adventure|Fantasy,2002.0
22,7153,0.719801,"Lord of the Rings: The Return of the King, The...",Action|Adventure|Drama|Fantasy,2003.0
1,260,0.704904,Star Wars: Episode IV - A New Hope (1977),Action|Adventure|Sci-Fi,1977.0
2,356,0.693831,Forrest Gump (1994),Comedy|Drama|Romance|War,1994.0
3,296,0.662548,Pulp Fiction (1994),Comedy|Crime|Drama|Thriller,1994.0
6,1196,0.617089,Star Wars: Episode V - The Empire Strikes Back...,Action|Adventure|Sci-Fi,1980.0
7,1198,0.595851,Raiders of the Lost Ark (Indiana Jones and the...,Action|Adventure,1981.0
8,1210,0.594467,Star Wars: Episode VI - Return of the Jedi (1983),Action|Adventure|Sci-Fi,1983.0
12,480,0.553318,Jurassic Park (1993),Action|Adventure|Sci-Fi|Thriller,1993.0
18,608,0.529056,Fargo (1996),Comedy|Crime|Drama|Thriller,1996.0
0,318,0.519418,"Shawshank Redemption, The (1994)",Crime|Drama,1994.0
4,2571,0.452444,"Matrix, The (1999)",Action|Sci-Fi|Thriller,1999.0
5,593,0.436230,"Silence of the Lambs, The (1991)",Crime|Horror|Thriller,1991.0
10,527,0.368920,Schindler's List (1993),Drama|War,1993.0
13,50,0.351459,"Usual Suspects, The (1995)",Crime|Mystery|Thriller,1995.0
14,589,0.346753,Terminator 2: Judgment Day (1991),Action|Sci-Fi,1991.0
15,2959,0.340188,Fight Club (1999),Action|Crime|Drama|Thriller,1999.0
16,858,0.337479,"Godfather, The (1972)",Crime|Drama,1972.0
17,110,0.333762,Braveheart (1995),Action|Drama|War,1995.0
21,47,0.322669,Seven (a.k.a. Se7en) (1995),Mystery|Thriller,1995.0
23,2028,0.311121,Saving Private Ryan (1998),Action|Drama|War,1998.0