In [1]:
import pandas as pd

In [2]:
moive_path = "movies.csv"
rating_path = "ratings.csv"
#links_path = "links.csv"
tags_path = "tags.csv"

In [3]:
movie_data = pd.read_csv(moive_path)
rating_data = pd.read_csv(rating_path)
# links_data = pd.read_csv(links_path)
#tag_data = pd.read_csv(tags_path)

In [4]:
#film_A = 1
#film_A = 191483 # The Nun (2018)
film_A = 106696 # frozen (2013)
#film_A = 85788 # insidios (2010)

här sätter folk betyget och vi sorterar att dom måste minst gett en 4a för att få vara en offentlig röst

In [5]:
liking_film_A = rating_data[
    (rating_data["movieId"] == film_A) & 
    (rating_data["rating"] >= 4.0) #minst 4 i betyg
            ].sort_values("userId")

ta alla filmer

In [6]:
users_A = liking_film_A["userId"].unique()

alla gillare från film A som gillar andra filmer

In [7]:
rekommend = rating_data[
    (rating_data["userId"].isin(users_A))&
    (rating_data["movieId"] != film_A)
            ].groupby("movieId").size()

In [8]:
score = rekommend / len(users_A)

In [9]:
try_top15 = (score.sort_values(ascending=False).head(25))

In [10]:
top15_score = try_top15.reset_index()
top15_score.columns = ["movieId", "score"]

top15 = top15_score.merge(movie_data, on="movieId")
top15

,movieId,score,title,genres
0,68954,0.763101,Up (2009),Adventure|Animation|Children|Drama
1,79132,0.738382,Inception (2010),Action|Crime|Drama|Mystery|Sci-Fi|Thriller|IMAX
2,60069,0.722761,WALL·E (2008),Adventure|Animation|Children|Romance|Sci-Fi
3,6377,0.720981,Finding Nemo (2003),Adventure|Animation|Children|Comedy
4,4993,0.719399,"Lord of the Rings: The Fellowship of the Ring,...",Adventure|Fantasy
5,4886,0.709709,"Monsters, Inc. (2001)",Adventure|Animation|Children|Comedy|Fantasy
6,7153,0.707930,"Lord of the Rings: The Return of the King, The...",Action|Adventure|Drama|Fantasy
7,2571,0.706941,"Matrix, The (1999)",Action|Sci-Fi|Thriller
8,4306,0.705359,Shrek (2001),Adventure|Animation|Children|Comedy|Fantasy|Ro...
9,5952,0.693890,"Lord of the Rings: The Two Towers, The (2002)",Adventure|Fantasy
10,58559,0.680245,"Dark Knight, The (2008)",Action|Crime|Drama|IMAX
11,134853,0.671347,Inside Out (2015),Adventure|Animation|Children|Comedy|Drama|Fantasy
12,8961,0.671149,"Incredibles, The (2004)",Action|Adventure|Animation|Children|Comedy
13,356,0.664030,Forrest Gump (1994),Comedy|Drama|Romance|War
14,50872,0.664030,Ratatouille (2007),Animation|Children|Drama
15,72998,0.659086,Avatar (2009),Action|Adventure|Sci-Fi|IMAX
16,6539,0.653945,Pirates of the Caribbean: The Curse of the Bla...,Action|Adventure|Comedy|Fantasy
17,59315,0.635357,Iron Man (2008),Action|Adventure|Sci-Fi
18,1,0.624876,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
19,112852,0.622306,Guardians of the Galaxy (2014),Action|Adventure|Sci-Fi
20,89745,0.617758,"Avengers, The (2012)",Action|Adventure|Sci-Fi|IMAX
21,318,0.613407,"Shawshank Redemption, The (1994)",Crime|Drama
22,260,0.607079,Star Wars: Episode IV - A New Hope (1977),Action|Adventure|Sci-Fi
23,76093,0.605497,How to Train Your Dragon (2010),Adventure|Animation|Children|Fantasy|IMAX
24,4896,0.601345,Harry Potter and the Sorcerer's Stone (a.k.a. ...,Adventure|Children|Fantasy

In [11]:
movie_data["year"] = movie_data["title"].str.extract(r"\((\d{4})\)").astype(float)

In [12]:
year_a = movie_data.loc[movie_data["movieId"] == film_A, "year"].iloc[0]
year_a

np.float64(2013.0)

In [13]:
top15

,movieId,score,title,genres
0,68954,0.763101,Up (2009),Adventure|Animation|Children|Drama
1,79132,0.738382,Inception (2010),Action|Crime|Drama|Mystery|Sci-Fi|Thriller|IMAX
2,60069,0.722761,WALL·E (2008),Adventure|Animation|Children|Romance|Sci-Fi
3,6377,0.720981,Finding Nemo (2003),Adventure|Animation|Children|Comedy
4,4993,0.719399,"Lord of the Rings: The Fellowship of the Ring,...",Adventure|Fantasy
5,4886,0.709709,"Monsters, Inc. (2001)",Adventure|Animation|Children|Comedy|Fantasy
6,7153,0.707930,"Lord of the Rings: The Return of the King, The...",Action|Adventure|Drama|Fantasy
7,2571,0.706941,"Matrix, The (1999)",Action|Sci-Fi|Thriller
8,4306,0.705359,Shrek (2001),Adventure|Animation|Children|Comedy|Fantasy|Ro...
9,5952,0.693890,"Lord of the Rings: The Two Towers, The (2002)",Adventure|Fantasy
10,58559,0.680245,"Dark Knight, The (2008)",Action|Crime|Drama|IMAX
11,134853,0.671347,Inside Out (2015),Adventure|Animation|Children|Comedy|Drama|Fantasy
12,8961,0.671149,"Incredibles, The (2004)",Action|Adventure|Animation|Children|Comedy
13,356,0.664030,Forrest Gump (1994),Comedy|Drama|Romance|War
14,50872,0.664030,Ratatouille (2007),Animation|Children|Drama
15,72998,0.659086,Avatar (2009),Action|Adventure|Sci-Fi|IMAX
16,6539,0.653945,Pirates of the Caribbean: The Curse of the Bla...,Action|Adventure|Comedy|Fantasy
17,59315,0.635357,Iron Man (2008),Action|Adventure|Sci-Fi
18,1,0.624876,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
19,112852,0.622306,Guardians of the Galaxy (2014),Action|Adventure|Sci-Fi
20,89745,0.617758,"Avengers, The (2012)",Action|Adventure|Sci-Fi|IMAX
21,318,0.613407,"Shawshank Redemption, The (1994)",Crime|Drama
22,260,0.607079,Star Wars: Episode IV - A New Hope (1977),Action|Adventure|Sci-Fi
23,76093,0.605497,How to Train Your Dragon (2010),Adventure|Animation|Children|Fantasy|IMAX
24,4896,0.601345,Harry Potter and the Sorcerer's Stone (a.k.a. ...,Adventure|Children|Fantasy

In [14]:
top15_year = top15.merge(movie_data, on=["movieId", "title", "genres"])
top15_year

,movieId,score,title,genres,year
0,68954,0.763101,Up (2009),Adventure|Animation|Children|Drama,2009.0
1,79132,0.738382,Inception (2010),Action|Crime|Drama|Mystery|Sci-Fi|Thriller|IMAX,2010.0
2,60069,0.722761,WALL·E (2008),Adventure|Animation|Children|Romance|Sci-Fi,2008.0
3,6377,0.720981,Finding Nemo (2003),Adventure|Animation|Children|Comedy,2003.0
4,4993,0.719399,"Lord of the Rings: The Fellowship of the Ring,...",Adventure|Fantasy,2001.0
5,4886,0.709709,"Monsters, Inc. (2001)",Adventure|Animation|Children|Comedy|Fantasy,2001.0
6,7153,0.707930,"Lord of the Rings: The Return of the King, The...",Action|Adventure|Drama|Fantasy,2003.0
7,2571,0.706941,"Matrix, The (1999)",Action|Sci-Fi|Thriller,1999.0
8,4306,0.705359,Shrek (2001),Adventure|Animation|Children|Comedy|Fantasy|Ro...,2001.0
9,5952,0.693890,"Lord of the Rings: The Two Towers, The (2002)",Adventure|Fantasy,2002.0
10,58559,0.680245,"Dark Knight, The (2008)",Action|Crime|Drama|IMAX,2008.0
11,134853,0.671347,Inside Out (2015),Adventure|Animation|Children|Comedy|Drama|Fantasy,2015.0
12,8961,0.671149,"Incredibles, The (2004)",Action|Adventure|Animation|Children|Comedy,2004.0
13,356,0.664030,Forrest Gump (1994),Comedy|Drama|Romance|War,1994.0
14,50872,0.664030,Ratatouille (2007),Animation|Children|Drama,2007.0
15,72998,0.659086,Avatar (2009),Action|Adventure|Sci-Fi|IMAX,2009.0
16,6539,0.653945,Pirates of the Caribbean: The Curse of the Bla...,Action|Adventure|Comedy|Fantasy,2003.0
17,59315,0.635357,Iron Man (2008),Action|Adventure|Sci-Fi,2008.0
18,1,0.624876,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,1995.0
19,112852,0.622306,Guardians of the Galaxy (2014),Action|Adventure|Sci-Fi,2014.0
20,89745,0.617758,"Avengers, The (2012)",Action|Adventure|Sci-Fi|IMAX,2012.0
21,318,0.613407,"Shawshank Redemption, The (1994)",Crime|Drama,1994.0
22,260,0.607079,Star Wars: Episode IV - A New Hope (1977),Action|Adventure|Sci-Fi,1977.0
23,76093,0.605497,How to Train Your Dragon (2010),Adventure|Animation|Children|Fantasy|IMAX,2010.0
24,4896,0.601345,Harry Potter and the Sorcerer's Stone (a.k.a. ...,Adventure|Children|Fantasy,2001.0

In [15]:
year_a

np.float64(2013.0)

In [16]:
top15_year["year"]

0     2009.0
1     2010.0
2     2008.0
3     2003.0
4     2001.0
5     2001.0
6     2003.0
7     1999.0
8     2001.0
9     2002.0
10    2008.0
11    2015.0
12    2004.0
13    1994.0
14    2007.0
15    2009.0
16    2003.0
17    2008.0
18    1995.0
19    2014.0
20    2012.0
21    1994.0
22    1977.0
23    2010.0
24    2001.0
Name: year, dtype: float64

In [17]:
diffrens_in_years = abs(top15_year["year"] - year_a)
diffrens_in_years

0      4.0
1      3.0
2      5.0
3     10.0
4     12.0
5     12.0
6     10.0
7     14.0
8     12.0
9     11.0
10     5.0
11     2.0
12     9.0
13    19.0
14     6.0
15     4.0
16    10.0
17     5.0
18    18.0
19     1.0
20     1.0
21    19.0
22    36.0
23     3.0
24    12.0
Name: year, dtype: float64

In [18]:
year_diffrens =diffrens_in_years.reset_index()
top15

,movieId,score,title,genres
0,68954,0.763101,Up (2009),Adventure|Animation|Children|Drama
1,79132,0.738382,Inception (2010),Action|Crime|Drama|Mystery|Sci-Fi|Thriller|IMAX
2,60069,0.722761,WALL·E (2008),Adventure|Animation|Children|Romance|Sci-Fi
3,6377,0.720981,Finding Nemo (2003),Adventure|Animation|Children|Comedy
4,4993,0.719399,"Lord of the Rings: The Fellowship of the Ring,...",Adventure|Fantasy
5,4886,0.709709,"Monsters, Inc. (2001)",Adventure|Animation|Children|Comedy|Fantasy
6,7153,0.707930,"Lord of the Rings: The Return of the King, The...",Action|Adventure|Drama|Fantasy
7,2571,0.706941,"Matrix, The (1999)",Action|Sci-Fi|Thriller
8,4306,0.705359,Shrek (2001),Adventure|Animation|Children|Comedy|Fantasy|Ro...
9,5952,0.693890,"Lord of the Rings: The Two Towers, The (2002)",Adventure|Fantasy
10,58559,0.680245,"Dark Knight, The (2008)",Action|Crime|Drama|IMAX
11,134853,0.671347,Inside Out (2015),Adventure|Animation|Children|Comedy|Drama|Fantasy
12,8961,0.671149,"Incredibles, The (2004)",Action|Adventure|Animation|Children|Comedy
13,356,0.664030,Forrest Gump (1994),Comedy|Drama|Romance|War
14,50872,0.664030,Ratatouille (2007),Animation|Children|Drama
15,72998,0.659086,Avatar (2009),Action|Adventure|Sci-Fi|IMAX
16,6539,0.653945,Pirates of the Caribbean: The Curse of the Bla...,Action|Adventure|Comedy|Fantasy
17,59315,0.635357,Iron Man (2008),Action|Adventure|Sci-Fi
18,1,0.624876,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
19,112852,0.622306,Guardians of the Galaxy (2014),Action|Adventure|Sci-Fi
20,89745,0.617758,"Avengers, The (2012)",Action|Adventure|Sci-Fi|IMAX
21,318,0.613407,"Shawshank Redemption, The (1994)",Crime|Drama
22,260,0.607079,Star Wars: Episode IV - A New Hope (1977),Action|Adventure|Sci-Fi
23,76093,0.605497,How to Train Your Dragon (2010),Adventure|Animation|Children|Fantasy|IMAX
24,4896,0.601345,Harry Potter and the Sorcerer's Stone (a.k.a. ...,Adventure|Children|Fantasy

In [19]:
top15_score

    movieId     score
0     68954  0.763101
1     79132  0.738382
2     60069  0.722761
3      6377  0.720981
4      4993  0.719399
5      4886  0.709709
6      7153  0.707930
7      2571  0.706941
8      4306  0.705359
9      5952  0.693890
10    58559  0.680245
11   134853  0.671347
12     8961  0.671149
13      356  0.664030
14    50872  0.664030
15    72998  0.659086
16     6539  0.653945
17    59315  0.635357
18        1  0.624876
19   112852  0.622306
20    89745  0.617758
21      318  0.613407
22      260  0.607079
23    76093  0.605497
24     4896  0.601345

In [20]:
top15_year["score"]

0     0.763101
1     0.738382
2     0.722761
3     0.720981
4     0.719399
5     0.709709
6     0.707930
7     0.706941
8     0.705359
9     0.693890
10    0.680245
11    0.671347
12    0.671149
13    0.664030
14    0.664030
15    0.659086
16    0.653945
17    0.635357
18    0.624876
19    0.622306
20    0.617758
21    0.613407
22    0.607079
23    0.605497
24    0.601345
Name: score, dtype: float64

In [21]:
for i in range(len(diffrens_in_years)):
    bonus = 0
    if int(year_diffrens["year"].loc[i]) <= 2:
        bonus = 1.15
        top15_year["score"].loc[i] *= bonus
    elif int(year_diffrens["year"].loc[i]) <= 5:
        bonus = 1.1
        top15_year["score"].loc[i] *= bonus
    elif int(year_diffrens["year"].loc[i]) <= 8:
        bonus = 1.05
        top15_year["score"].loc[i] *= bonus

    else:
        top15_year["score"].loc[i]

C:\Users\stegi\AppData\Local\Temp\ipykernel_22004\2650024771.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  top15_year["score"].loc[i] *= bonus
C:\Users\stegi\AppData\Local\Temp\ipykernel_22004\2650024771.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  top15_year["score"].loc[i] *= bonus
C:\Users\stegi\AppData\Local\Temp\ipykernel_22004\2650024771.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  top15_year["score"].loc[i] *= bonus
C:\Users\stegi\AppData\Local\Temp\ipykernel_22004\2650024771.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  top15_year["score"].loc[i] *= bonus
C:\Users\stegi\AppData\Local\Temp\ipykernel_22004\2650024771.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  top15_year["score"].loc[i] *= bonus
C:\Users\stegi\AppData\Local\Temp\ipykernel_22004\2650024771.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  top15_year["score"].loc[i] *= bonus
C:\Users\stegi\AppData\Local\Temp\ipykernel_22004\2650024771.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  top15_year["score"].loc[i] *= bonus
C:\Users\stegi\AppData\Local\Temp\ipykernel_22004\2650024771.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  top15_year["score"].loc[i] *= bonus
C:\Users\stegi\AppData\Local\Temp\ipykernel_22004\2650024771.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  top15_year["score"].loc[i] *= bonus
C:\Users\stegi\AppData\Local\Temp\ipykernel_22004\2650024771.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  top15_year["score"].loc[i] *= bonus
C:\Users\stegi\AppData\Local\Temp\ipykernel_22004\2650024771.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  top15_year["score"].loc[i] *= bonus

In [22]:
movie_data[movie_data["movieId"] == 85788]

       movieId             title                   genres    year
16231    85788  Insidious (2010)  Fantasy|Horror|Thriller  2010.0

In [23]:
top = top15_year.sort_values("score", ascending=False)
top

,movieId,score,title,genres,year
0,68954,0.839411,Up (2009),Adventure|Animation|Children|Drama,2009.0
1,79132,0.812221,Inception (2010),Action|Crime|Drama|Mystery|Sci-Fi|Thriller|IMAX,2010.0
2,60069,0.795037,WALL·E (2008),Adventure|Animation|Children|Romance|Sci-Fi,2008.0
11,134853,0.772049,Inside Out (2015),Adventure|Animation|Children|Comedy|Drama|Fantasy,2015.0
10,58559,0.748270,"Dark Knight, The (2008)",Action|Crime|Drama|IMAX,2008.0
15,72998,0.724995,Avatar (2009),Action|Adventure|Sci-Fi|IMAX,2009.0
3,6377,0.720981,Finding Nemo (2003),Adventure|Animation|Children|Comedy,2003.0
4,4993,0.719399,"Lord of the Rings: The Fellowship of the Ring,...",Adventure|Fantasy,2001.0
19,112852,0.715652,Guardians of the Galaxy (2014),Action|Adventure|Sci-Fi,2014.0
20,89745,0.710421,"Avengers, The (2012)",Action|Adventure|Sci-Fi|IMAX,2012.0
5,4886,0.709709,"Monsters, Inc. (2001)",Adventure|Animation|Children|Comedy|Fantasy,2001.0
6,7153,0.707930,"Lord of the Rings: The Return of the King, The...",Action|Adventure|Drama|Fantasy,2003.0
7,2571,0.706941,"Matrix, The (1999)",Action|Sci-Fi|Thriller,1999.0
8,4306,0.705359,Shrek (2001),Adventure|Animation|Children|Comedy|Fantasy|Ro...,2001.0
17,59315,0.698893,Iron Man (2008),Action|Adventure|Sci-Fi,2008.0
14,50872,0.697232,Ratatouille (2007),Animation|Children|Drama,2007.0
9,5952,0.693890,"Lord of the Rings: The Two Towers, The (2002)",Adventure|Fantasy,2002.0
12,8961,0.671149,"Incredibles, The (2004)",Action|Adventure|Animation|Children|Comedy,2004.0
23,76093,0.666047,How to Train Your Dragon (2010),Adventure|Animation|Children|Fantasy|IMAX,2010.0
13,356,0.664030,Forrest Gump (1994),Comedy|Drama|Romance|War,1994.0
16,6539,0.653945,Pirates of the Caribbean: The Curse of the Bla...,Action|Adventure|Comedy|Fantasy,2003.0
18,1,0.624876,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,1995.0
21,318,0.613407,"Shawshank Redemption, The (1994)",Crime|Drama,1994.0
22,260,0.607079,Star Wars: Episode IV - A New Hope (1977),Action|Adventure|Sci-Fi,1977.0
24,4896,0.601345,Harry Potter and the Sorcerer's Stone (a.k.a. ...,Adventure|Children|Fantasy,2001.0

In [24]:
a = movie_data[movie_data["movieId"] == 85788]
A = a["genres"].iloc[0].split("|")
A

['Fantasy', 'Horror', 'Thriller']

In [25]:
A = movie_data[movie_data["movieId"] == film_A]["genres"].iloc[0].split("|")

for idx, genres in enumerate(top["genres"]):

    genre_list = genres.split("|")

    for g in genre_list:
        if g in A:
            print(top["title"].iloc[idx])
            top["score"].iloc[idx] += 0.5

Up (2009)
Up (2009)
WALL·E (2008)
WALL·E (2008)
WALL·E (2008)
Inside Out (2015)
Inside Out (2015)
Inside Out (2015)
Inside Out (2015)
Avatar (2009)
Finding Nemo (2003)
Finding Nemo (2003)
Finding Nemo (2003)
Lord of the Rings: The Fellowship of the Ring, The (2001)
Lord of the Rings: The Fellowship of the Ring, The (2001)
Guardians of the Galaxy (2014)
Avengers, The (2012)
Monsters, Inc. (2001)
Monsters, Inc. (2001)
Monsters, Inc. (2001)
Monsters, Inc. (2001)
Lord of the Rings: The Return of the King, The (2003)
Lord of the Rings: The Return of the King, The (2003)
Shrek (2001)
Shrek (2001)
Shrek (2001)
Shrek (2001)
Shrek (2001)
Iron Man (2008)
Ratatouille (2007)
Lord of the Rings: The Two Towers, The (2002)
Lord of the Rings: The Two Towers, The (2002)
Incredibles, The (2004)
Incredibles, The (2004)
Incredibles, The (2004)
How to Train Your Dragon (2010)
How to Train Your Dragon (2010)
How to Train Your Dragon (2010)
Forrest Gump (1994)
Forrest Gump (1994)
Pirates of the Caribbean: The Curse of the Black Pearl (2003)
Pirates of the Caribbean: The Curse of the Black Pearl (2003)
Pirates of the Caribbean: The Curse of the Black Pearl (2003)
Toy Story (1995)
Toy Story (1995)
Toy Story (1995)
Toy Story (1995)
Star Wars: Episode IV - A New Hope (1977)
Harry Potter and the Sorcerer's Stone (a.k.a. Harry Potter and the Philosopher's Stone) (2001)
Harry Potter and the Sorcerer's Stone (a.k.a. Harry Potter and the Philosopher's Stone) (2001)

C:\Users\stegi\AppData\Local\Temp\ipykernel_22004\2193459521.py:10: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  top["score"].iloc[idx] += 0.5
C:\Users\stegi\AppData\Local\Temp\ipykernel_22004\2193459521.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  top["score"].iloc[idx] += 0.5
C:\Users\stegi\AppData\Local\Temp\ipykernel_22004\2193459521.py:10: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  top["score"].iloc[idx] += 0.5
C:\Users\stegi\AppData\Local\Temp\ipykernel_22004\2193459521.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  top["score"].iloc[idx] += 0.5
C:\Users\stegi\AppData\Local\Temp\ipykernel_22004\2193459521.py:10: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  top["score"].iloc[idx] += 0.5
C:\Users\stegi\AppData\Local\Temp\ipykernel_22004\2193459521.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  top["score"].iloc[idx] += 0.5
C:\Users\stegi\AppData\Local\Temp\ipykernel_22004\2193459521.py:10: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  top["score"].iloc[idx] += 0.5
C:\Users\stegi\AppData\Local\Temp\ipykernel_22004\2193459521.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  top["score"].iloc[idx] += 0.5
C:\Users\stegi\AppData\Local\Temp\ipykernel_22004\2193459521.py:10: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  top["score"].iloc[idx] += 0.5
C:\Users\stegi\AppData\Local\Temp\ipykernel_22004\2193459521.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  top["score"].iloc[idx] += 0.5
C:\Users\stegi\AppData\Local\Temp\ipykernel_22004\2193459521.py:10: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  top["score"].iloc[idx] += 0.5
C:\Users\stegi\AppData\Local\Temp\ipykernel_22004\2193459521.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  top["score"].iloc[idx] += 0.5
C:\Users\stegi\AppData\Local\Temp\ipykernel_22004\2193459521.py:10: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  top["score"].iloc[idx] += 0.5
C:\Users\stegi\AppData\Local\Temp\ipykernel_22004\2193459521.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  top["score"].iloc[idx] += 0.5
C:\Users\stegi\AppData\Local\Temp\ipykernel_22004\2193459521.py:10: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  top["score"].iloc[idx] += 0.5
C:\Users\stegi\AppData\Local\Temp\ipykernel_22004\2193459521.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  top["score"].iloc[idx] += 0.5
C:\Users\stegi\AppData\Local\Temp\ipykernel_22004\2193459521.py:10: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  top["score"].iloc[idx] += 0.5
C:\Users\stegi\AppData\Local\Temp\ipykernel_22004\2193459521.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  top["score"].iloc[idx] += 0.5
C:\Users\stegi\AppData\Local\Temp\ipykernel_22004\2193459521.py:10: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  top["score"].iloc[idx] += 0.5
C:\Users\stegi\AppData\Local\Temp\ipykernel_22004\2193459521.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  top["score"].iloc[idx] += 0.5
C:\Users\stegi\AppData\Local\Temp\ipykernel_22004\2193459521.py:10: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  top["score"].iloc[idx] += 0.5
C:\Users\stegi\AppData\Local\Temp\ipykernel_22004\2193459521.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  top["score"].iloc[idx] += 0.5
C:\Users\stegi\AppData\Local\Temp\ipykernel_22004\2193459521.py:10: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  top["score"].iloc[idx] += 0.5
C:\Users\stegi\AppData\Local\Temp\ipykernel_22004\2193459521.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  top["score"].iloc[idx] += 0.5
C:\Users\stegi\AppData\Local\Temp\ipykernel_22004\2193459521.py:10: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  top["score"].iloc[idx] += 0.5
C:\Users\stegi\AppData\Local\Temp\ipykernel_22004\2193459521.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  top["score"].iloc[idx] += 0.5
C:\Users\stegi\AppData\Local\Temp\ipykernel_22004\2193459521.py:10: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  top["score"].iloc[idx] += 0.5
C:\Users\stegi\AppData\Local\Temp\ipykernel_22004\2193459521.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  top["score"].iloc[idx] += 0.5
C:\Users\stegi\AppData\Local\Temp\ipykernel_22004\2193459521.py:10: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  top["score"].iloc[idx] += 0.5
C:\Users\stegi\AppData\Local\Temp\ipykernel_22004\2193459521.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  top["score"].iloc[idx] += 0.5
C:\Users\stegi\AppData\Local\Temp\ipykernel_22004\2193459521.py:10: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  top["score"].iloc[idx] += 0.5
C:\Users\stegi\AppData\Local\Temp\ipykernel_22004\2193459521.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  top["score"].iloc[idx] += 0.5
C:\Users\stegi\AppData\Local\Temp\ipykernel_22004\2193459521.py:10: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!

In [26]:
# b = -1
# for idx, genres in enumerate(top["genres"]):
#     a = i.split("|")
#     b += 1
#     for j in a:
#         if j in A:
#             print(top["title"].loc[b])            
#             top["score"].loc[b] += 0.1

In [27]:
top.sort_values("score", ascending=False)

,movieId,score,title,genres,year
8,4306,3.205359,Shrek (2001),Adventure|Animation|Children|Comedy|Fantasy|Ro...,2001.0
11,134853,2.772049,Inside Out (2015),Adventure|Animation|Children|Comedy|Drama|Fantasy,2015.0
5,4886,2.709709,"Monsters, Inc. (2001)",Adventure|Animation|Children|Comedy|Fantasy,2001.0
18,1,2.624876,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,1995.0
2,60069,2.295037,WALL·E (2008),Adventure|Animation|Children|Romance|Sci-Fi,2008.0
3,6377,2.220981,Finding Nemo (2003),Adventure|Animation|Children|Comedy,2003.0
12,8961,2.171149,"Incredibles, The (2004)",Action|Adventure|Animation|Children|Comedy,2004.0
23,76093,2.166047,How to Train Your Dragon (2010),Adventure|Animation|Children|Fantasy|IMAX,2010.0
16,6539,2.153945,Pirates of the Caribbean: The Curse of the Bla...,Action|Adventure|Comedy|Fantasy,2003.0
0,68954,1.839411,Up (2009),Adventure|Animation|Children|Drama,2009.0
4,4993,1.719399,"Lord of the Rings: The Fellowship of the Ring,...",Adventure|Fantasy,2001.0
6,7153,1.707930,"Lord of the Rings: The Return of the King, The...",Action|Adventure|Drama|Fantasy,2003.0
9,5952,1.693890,"Lord of the Rings: The Two Towers, The (2002)",Adventure|Fantasy,2002.0
13,356,1.664030,Forrest Gump (1994),Comedy|Drama|Romance|War,1994.0
24,4896,1.601345,Harry Potter and the Sorcerer's Stone (a.k.a. ...,Adventure|Children|Fantasy,2001.0
15,72998,1.224995,Avatar (2009),Action|Adventure|Sci-Fi|IMAX,2009.0
19,112852,1.215652,Guardians of the Galaxy (2014),Action|Adventure|Sci-Fi,2014.0
20,89745,1.210421,"Avengers, The (2012)",Action|Adventure|Sci-Fi|IMAX,2012.0
17,59315,1.198893,Iron Man (2008),Action|Adventure|Sci-Fi,2008.0
14,50872,1.197232,Ratatouille (2007),Animation|Children|Drama,2007.0
22,260,1.107079,Star Wars: Episode IV - A New Hope (1977),Action|Adventure|Sci-Fi,1977.0
1,79132,0.812221,Inception (2010),Action|Crime|Drama|Mystery|Sci-Fi|Thriller|IMAX,2010.0
10,58559,0.748270,"Dark Knight, The (2008)",Action|Crime|Drama|IMAX,2008.0
7,2571,0.706941,"Matrix, The (1999)",Action|Sci-Fi|Thriller,1999.0
21,318,0.613407,"Shawshank Redemption, The (1994)",Crime|Drama,1994.0

In [28]:
top15.sort_values("score",ascending=False)

,movieId,score,title,genres
0,68954,0.763101,Up (2009),Adventure|Animation|Children|Drama
1,79132,0.738382,Inception (2010),Action|Crime|Drama|Mystery|Sci-Fi|Thriller|IMAX
2,60069,0.722761,WALL·E (2008),Adventure|Animation|Children|Romance|Sci-Fi
3,6377,0.720981,Finding Nemo (2003),Adventure|Animation|Children|Comedy
4,4993,0.719399,"Lord of the Rings: The Fellowship of the Ring,...",Adventure|Fantasy
5,4886,0.709709,"Monsters, Inc. (2001)",Adventure|Animation|Children|Comedy|Fantasy
6,7153,0.707930,"Lord of the Rings: The Return of the King, The...",Action|Adventure|Drama|Fantasy
7,2571,0.706941,"Matrix, The (1999)",Action|Sci-Fi|Thriller
8,4306,0.705359,Shrek (2001),Adventure|Animation|Children|Comedy|Fantasy|Ro...
9,5952,0.693890,"Lord of the Rings: The Two Towers, The (2002)",Adventure|Fantasy
10,58559,0.680245,"Dark Knight, The (2008)",Action|Crime|Drama|IMAX
11,134853,0.671347,Inside Out (2015),Adventure|Animation|Children|Comedy|Drama|Fantasy
12,8961,0.671149,"Incredibles, The (2004)",Action|Adventure|Animation|Children|Comedy
13,356,0.664030,Forrest Gump (1994),Comedy|Drama|Romance|War
14,50872,0.664030,Ratatouille (2007),Animation|Children|Drama
15,72998,0.659086,Avatar (2009),Action|Adventure|Sci-Fi|IMAX
16,6539,0.653945,Pirates of the Caribbean: The Curse of the Bla...,Action|Adventure|Comedy|Fantasy
17,59315,0.635357,Iron Man (2008),Action|Adventure|Sci-Fi
18,1,0.624876,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
19,112852,0.622306,Guardians of the Galaxy (2014),Action|Adventure|Sci-Fi
20,89745,0.617758,"Avengers, The (2012)",Action|Adventure|Sci-Fi|IMAX
21,318,0.613407,"Shawshank Redemption, The (1994)",Crime|Drama
22,260,0.607079,Star Wars: Episode IV - A New Hope (1977),Action|Adventure|Sci-Fi
23,76093,0.605497,How to Train Your Dragon (2010),Adventure|Animation|Children|Fantasy|IMAX
24,4896,0.601345,Harry Potter and the Sorcerer's Stone (a.k.a. ...,Adventure|Children|Fantasy

In [29]:
movie_data[movie_data["title"] == "Insidious: The Last Key (2018)"]

,movieId,title,genres,year
52175,183295,Insidious: The Last Key (2018),Horror|Mystery|Thriller,2018.0

In [44]:
genrer = movie_data[movie_data["movieId"] == film_A]
genrer["genres"].value_counts()

genres
Adventure|Animation|Comedy|Fantasy|Musical|Romance    1
Name: count, dtype: int64

In [ ]:
top15

,movieId,score,title,genres
0,68954,0.763101,Up (2009),Adventure|Animation|Children|Drama
1,79132,0.738382,Inception (2010),Action|Crime|Drama|Mystery|Sci-Fi|Thriller|IMAX
2,60069,0.722761,WALL·E (2008),Adventure|Animation|Children|Romance|Sci-Fi
3,6377,0.720981,Finding Nemo (2003),Adventure|Animation|Children|Comedy
4,4993,0.719399,"Lord of the Rings: The Fellowship of the Ring,...",Adventure|Fantasy
5,4886,0.709709,"Monsters, Inc. (2001)",Adventure|Animation|Children|Comedy|Fantasy
6,7153,0.707930,"Lord of the Rings: The Return of the King, The...",Action|Adventure|Drama|Fantasy
7,2571,0.706941,"Matrix, The (1999)",Action|Sci-Fi|Thriller
8,4306,0.705359,Shrek (2001),Adventure|Animation|Children|Comedy|Fantasy|Ro...
9,5952,0.693890,"Lord of the Rings: The Two Towers, The (2002)",Adventure|Fantasy
10,58559,0.680245,"Dark Knight, The (2008)",Action|Crime|Drama|IMAX
11,134853,0.671347,Inside Out (2015),Adventure|Animation|Children|Comedy|Drama|Fantasy
12,8961,0.671149,"Incredibles, The (2004)",Action|Adventure|Animation|Children|Comedy
13,356,0.664030,Forrest Gump (1994),Comedy|Drama|Romance|War
14,50872,0.664030,Ratatouille (2007),Animation|Children|Drama
15,72998,0.659086,Avatar (2009),Action|Adventure|Sci-Fi|IMAX
16,6539,0.653945,Pirates of the Caribbean: The Curse of the Bla...,Action|Adventure|Comedy|Fantasy
17,59315,0.635357,Iron Man (2008),Action|Adventure|Sci-Fi
18,1,0.624876,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
19,112852,0.622306,Guardians of the Galaxy (2014),Action|Adventure|Sci-Fi
20,89745,0.617758,"Avengers, The (2012)",Action|Adventure|Sci-Fi|IMAX
21,318,0.613407,"Shawshank Redemption, The (1994)",Crime|Drama
22,260,0.607079,Star Wars: Episode IV - A New Hope (1977),Action|Adventure|Sci-Fi
23,76093,0.605497,How to Train Your Dragon (2010),Adventure|Animation|Children|Fantasy|IMAX
24,4896,0.601345,Harry Potter and the Sorcerer's Stone (a.k.a. ...,Adventure|Children|Fantasy

In [31]:
movie_data[movie_data["title"] == "Frozen (2013)"]

,movieId,title,genres,year
20648,106696,Frozen (2013),Adventure|Animation|Comedy|Fantasy|Musical|Rom...,2013.0

In [49]:
top15_year.sort_values("year",ascending=False)

,movieId,score,title,genres,year
11,134853,0.772049,Inside Out (2015),Adventure|Animation|Children|Comedy|Drama|Fantasy,2015.0
19,112852,0.715652,Guardians of the Galaxy (2014),Action|Adventure|Sci-Fi,2014.0
20,89745,0.710421,"Avengers, The (2012)",Action|Adventure|Sci-Fi|IMAX,2012.0
23,76093,0.666047,How to Train Your Dragon (2010),Adventure|Animation|Children|Fantasy|IMAX,2010.0
1,79132,0.812221,Inception (2010),Action|Crime|Drama|Mystery|Sci-Fi|Thriller|IMAX,2010.0
0,68954,0.839411,Up (2009),Adventure|Animation|Children|Drama,2009.0
15,72998,0.724995,Avatar (2009),Action|Adventure|Sci-Fi|IMAX,2009.0
17,59315,0.698893,Iron Man (2008),Action|Adventure|Sci-Fi,2008.0
2,60069,0.795037,WALL·E (2008),Adventure|Animation|Children|Romance|Sci-Fi,2008.0
10,58559,0.748270,"Dark Knight, The (2008)",Action|Crime|Drama|IMAX,2008.0
14,50872,0.697232,Ratatouille (2007),Animation|Children|Drama,2007.0
12,8961,0.671149,"Incredibles, The (2004)",Action|Adventure|Animation|Children|Comedy,2004.0
16,6539,0.653945,Pirates of the Caribbean: The Curse of the Bla...,Action|Adventure|Comedy|Fantasy,2003.0
6,7153,0.707930,"Lord of the Rings: The Return of the King, The...",Action|Adventure|Drama|Fantasy,2003.0
3,6377,0.720981,Finding Nemo (2003),Adventure|Animation|Children|Comedy,2003.0
9,5952,0.693890,"Lord of the Rings: The Two Towers, The (2002)",Adventure|Fantasy,2002.0
4,4993,0.719399,"Lord of the Rings: The Fellowship of the Ring,...",Adventure|Fantasy,2001.0
5,4886,0.709709,"Monsters, Inc. (2001)",Adventure|Animation|Children|Comedy|Fantasy,2001.0
8,4306,0.705359,Shrek (2001),Adventure|Animation|Children|Comedy|Fantasy|Ro...,2001.0
24,4896,0.601345,Harry Potter and the Sorcerer's Stone (a.k.a. ...,Adventure|Children|Fantasy,2001.0
7,2571,0.706941,"Matrix, The (1999)",Action|Sci-Fi|Thriller,1999.0
18,1,0.624876,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,1995.0
13,356,0.664030,Forrest Gump (1994),Comedy|Drama|Romance|War,1994.0
21,318,0.613407,"Shawshank Redemption, The (1994)",Crime|Drama,1994.0
22,260,0.607079,Star Wars: Episode IV - A New Hope (1977),Action|Adventure|Sci-Fi,1977.0